require: rubocop-minitest

inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "acceptance/**/*"
    - "conformance/**/*"
    - "google-cloud-storage.gemspec"
    - "Rakefile"
    - "test/**/*"
    - "support/**/*"

Documentation:
  Enabled: false

Layout/AlignHash:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Max: 40
Naming/FileName:
  Exclude:
    - "lib/google-cloud-storage.rb"
Style/IfUnlessModifier:
  Enabled: false
Style/MethodDefParentheses:
  Exclude:
    - "lib/google/cloud/storage/policy.rb"
Style/NumericPredicate:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/UnpackFirst:
  Enabled: false
Style/WordArray:
  Enabled: false
